# @COPYRIGHT@
# Licensed under MIT license (LICENSE.txt).

Import('env')

for src in env.Glob('*.cpp'):
    env.Program(src)

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
