# @COPYRIGHT@
# Licensed under MIT license (LICENSE.txt).

Import(['env'])

from SCons.Util import CLVar

tests = [
    'detail/algo_search.t.h',
#    'detail/bspline_1d_nu.t.h',
    'detail/ppfun_1d_nu.t.h',
    'opencl/env.t.h',
    'opencl/util/type_to_string.t.h',
    'opencl/programs/search_interval.t.h',
    'opencl/static_program_generator.t.h',
#    'opencl/programs/ppfun_1d_nu.t.h',
]

env.CxxTest('../check-libnumbo', tests,
           LIBS = CLVar('clxx_cl'),
           CXXTEST_CPPPATH = ['..'],
           CXXTEST_LIBPATH = env.get('LIBPATH', CLVar()),
           CXXTEST_TARGET = 'check-libnumbo')

env.Alias('check', [ 'check-libnumbo' ])
env.AlwaysBuild('check-libnumbo')

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
