# @COPYRIGHT@
# Licensed under MIT license (LICENSE.txt).

Import('env')

subdirs = [ 'kernels' ]
scripts = [ '%s/SConscript' % s for s in subdirs ]
SConscript(scripts, exports = ['env'])

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
